version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: chatapp_postgres
    environment:
      POSTGRES_DB: realtime_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatapp_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatapp_backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: realtime_chat
      DB_USERNAME: postgres
      DB_PASSWORD: password
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - chatapp_network
    command: npm run dev

  nginx:
    image: nginx:alpine
    container_name: chatapp_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - chatapp_network

volumes:
  postgres_data:

networks:
  chatapp_network:
    driver: bridge